### ISSUE TITLE
Snowboy -> Google Speech-to-Text

### ISSUE THREAD

**Issue by ipernjakovic** [BlackLight/platypush#139]
Hi,

just wondering is there a plugin that would do that? Quite similar to Google Assistant integration, only after detecting a Snowboy hotword, redirecting the audio to Google Speech-to-Text API and getting back a transcription of the audio?

thanks
Ivan

**Comment by BlackLight** [comment]
You can link a Snowboy hotword to e.g. the Google push-to-talk integration (or whichever assistant plugin you prefer):

```yaml
backend.assistant.snowboy:
    audio_gain: 1.0

    models:
        smart_mirror:
            voice_model_file: ~/.local/share/snowboy/models/smart_mirror.umdl
            assistant_plugin: assistant.google.pushtotalk
            assistant_language: en-US
            detect_sound: ~/your/sound.wav
            sensitivity: 0.5
```

Then if you use push-to-talk you can either configure it with `play_response=False` so it won't play the response, and instead react on the `ResponseEvent`:

```yaml
assistant.google.pushtotalk:
    play_response: False

event.hook.OnResponse:
    if:
        type: platypush.message.event.assistant.ResponseEvent
    then:
        - action: tts.google.say
          args:
              text: ${response_text}
```

Or directly set the `tts_plugin` option:

```yaml
assistant.google.pushtotalk:
    play_response: False
    tts_plugin: tts.google
```
