### ISSUE TITLE
This site can’t be reached - http://hostname:8008/

### ISSUE THREAD

**Issue by billwatsonaz** [BlackLight/platypush#157]
Hi All - 

First, I really appreciate this application and your post about creating a z-wave bridge. I think we fixed all our install issues on our Raspberry Pi by using Python3. We have made it through all of the install steps and created a config file using everything in the example file but we focused on the following:

```
backend.http:
    # Listening port
    port: 8008
    websocket_port: 8009

zwave:
    device: /dev/ttyUSB3
backend.zwave:
    enabled: true
```

We were able to start the service by creating blank loggging.yaml and media.yaml, but now when we try to access the HTTP backend at http://hostname:8008/ we get the error "This site can’t be reached".

Looking forward to getting this working. Thanks for all of your help!

**Comment by BlackLight** [comment]
The right configuration should be something like this (the zwave plugin/backend split is a bit confusing for now, but I'm planning to fix it):

```yaml
backend.http:
    port: 8008
    websocket_port: 8009

zwave:
    enabled: true

backend.zwave:
    device: /dev/ttyUSB3
```

Also, blank `logging.yaml` and `media.yaml` are not required - you can simply remove those files from the `include` section of `config.yaml` and they won't be searched.

The hostname in `hostname:8008` should point to the hostname/IP address of the device. If that doesn't work could you paste the logs of the application? It may be that some other zombie Platypush process is occupying the port.
