### ISSUE TITLE
Allow sequential actions in procedures and hooks

### ISSUE THREAD

**Issue by BlackLight** [BlackLight/platypush#37]
The action sequences are executed asynchronously as of now. In some contexts though you may want to execute a certain action only when the previous one completed, or build part of the logic using the result of the previous action. We should support a configuration syntax like:

```yaml
if:
  - some condition
then:
  serial:
    - action 1
    - action 2 --arg $response.status
```
