### ISSUE TITLE
Implement for loops in procedures

### ISSUE THREAD

**Issue by BlackLight** [BlackLight/platypush#44]
It should be possible to loop over lists through a simple `for` loop in a synchronous procedure.

Example:

```yaml
procedure.sync.process_results:
-
    action: http.get
    args:
        url: https://some-service/some/json/endpoint
        # Example response: { "results": [ {"id":1, "name":"foo"}, {"id":2,"name":"bar"} ]}
-
    for result in ${results}:
        -
            action: some.custom.action
            args:
                id: ${result['id']}
                name: ${result['name']}
```
